baseURL = "http://open-cluster-management.io"
languageCode = "en-us"
theme = "ocmTheme"

contentDir = "content"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[Permalinks]
code = "/:filename/"

[params]
title = "Open Cluster Management"
description = "Open Cluster Management is the best way to simplify management of multiple Kubernetes clusters."
jsFile = [
  "app"
]


# i18n menu configs

# English
[languages.en]
title = "Open Cluster Management"
description = "Open Cluster Management is the best way to simplify management of multiple Kubernetes clusters."
contentDir = "content/en"
languageName = "English"
weight = 1


[[languages.en.menu.main]]
  name = "Getting started"
  url = "/getting-started/quick-start"
  weight = 1
[[languages.en.menu.main]]
  name = "Docs"
  url = "/concepts/addon"
  weight = 2
[[languages.en.menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3
[[languages.en.menu.main]]
  name = "Community"
  url = "/community"
  weight = 3
[[languages.en.menu.main]]
  name = "Contribute"
  url = "/contribute"
  weight = 4