
name = "open cluster management"
license = "MIT"
licenselink = "https://github.com/open-cluster-management-io/open-cluster-management-io.github.io"
description = "Theme for Open Cluster Management Project"
homepage = "https://github.com/open-cluster-management"
tags = ["open cluster management", "kubernetes", "cluster"]
